### ISSUE TITLE
보완할거

### ISSUE THREAD

**Issue by cherry-in** [kucc/KUCheckCheck#102]
- [x] 사용자 계정 삭제

- [x] 삭제된 사용자의 세션 관리
현재 진행중인 세션장이 탈퇴를 했을 경우

**Comment by qqq1212341** [comment]
- 마이 페이지 수정하기 모달에 탈퇴하기 버튼 생성하고.. 
- 탈퇴시 유저가 존재하는 모든 세션에서 유저 제거 ( 출석 정보도 함께 제거해야함), 만약 세션장이라면 세션을 삭제
<br/> 를 하면 될거 같슴다!! 구현해볼게여~~

**Comment by qqq1212341** [comment]
해결완료 ~~ #104
