### ISSUE TITLE
Nav Bar 수정

### ISSUE THREAD

**Issue by JayMyong66** [kucc/KUCheckCheck#32]
# 설명
App.js로 빼주기  -  main 페이지에서는..? → 주소따서 radius, shadow 없애주기.
- [x] StyledBackground (배경색 통일)
- [x] main page에서 radius, shadow 빼기
- [x] 모든 페이지 NavBar 수정
- [ ] #54

**Comment by qqq1212341** [comment]
#33 이거 하면서 radius, shadow는 해결했슴다!
