### ISSUE TITLE
페이지 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by saygenie** [kucc/KUCheckCheck#34]
# 설명
현재 페이지명에 대한 통일성이 없기 때문에 `/pages/` 아래에 있는 페이지들의 이름 변경해야 한다.

- [x] `/pages/` 아래에 있는 폴더 및 컴포넌트 이름 변경하기
  - 메인 페이지: MainPage
  - 코스 상세 정보: CoursePage
  - 코스 등록하기: CourseRegisterPage
  - 공지사항: NoticePage
  - 로그인 페이지: LoginPage
  - 회원가입 페이지: JoinPage
  - 시간표 확인하기: TimeTablePage
  - 출결확인: AttendancePage

**Comment by saygenie** [comment]
- [ ] Course 폴더 안에서 CourseAttendance 분리

**Comment by qqq1212341** [comment]
파일 명 변경에 따른 라우터 이름 변경?
ex : /course-new => /course/register
