### ISSUE TITLE
Utility 폴더 생성

### ISSUE THREAD

**Issue by qqq1212341** [kucc/KUCheckCheck#35]
# 생성
Utility 폴더 생성, constants 폴더 삭제
Utility
---ERROR_MESSAGE.js
---CONSTANTS.js => timetable 등에서 쓰이는 상수
---RANDOM_EMOJI.js => 이모지 함수
---COLORS.js => 색깔들 모아둔 곳
---COMMON_STYLE.js => 자주 쓰이는 styled component들을 모아둔 곳(상속할 애들도 포함!)

- [x] ERROR_MESSAGE.js
- [x] CONSTANTS.js 
- [x] RANDOM_EMOJI.js

**Comment by saygenie** [comment]
@qqq1212341 document label은 README 파일이나 주석 같이 코드에 영향을 주지 않는 경우 쓰면 좋을 것 같음.

**Comment by qqq1212341** [comment]
아하.. 문서 관련 내용인줄 알았슴다 수정할게욥!
