### ISSUE TITLE
재사용 컴포넌트

### ISSUE THREAD

**Issue by cherry-in** [kucc/KUCheckCheck#36]
# 설명
재사용하는 컴포넌트는 `components/` 폴더에 생성

- [x] 등록하기 버튼
  - props로 넘겨줄것 : text, color(테마?), onClick() 등등
  - 수강인원 실시간 숫자 처리?

- [ ] main 코스 카드
  - 

- [x] ShadowBox 
  - 원래 InnerShadowToggle  였던것.
  - 그림자 옵션 : in / out-연 / out-진

- [x] InnerShadowInput 
  -  Compenets / InputBoxWithLabel  

메인페이지의 세션 view 재사용

버튼모양 선택하는 컴포넌트 재사용 → 안쪽으로 들어간 버튼 ( InnerShadowToggle ) , 바깥쪽으로 튀어나온 버튼

InnerShadowInput → Compenets / InputBoxWithLabel   여기 있음.    (ex) CourseNew에

className으로 shadow 등의 설정.

**Comment by qqq1212341** [comment]
UserPage > UserInfo > UserInfoCard에 들어있는 StyledInfoIconContainer와
MainPage > MainSearch에 들어있는 StyledIconContainer는 기능이 같으므로 components화 시키면 좋을 듯 합니다.

**Comment by qqq1212341** [comment]
className으로 shadow 설정하는 것은 #33 을 진행하며 다 리팩토링 했슴니다!
