### ISSUE TITLE
수정모드 개선하기

### ISSUE THREAD

**Issue by saygenie** [kucc/KUCheckCheck#37]
### Problems
코스를 수정하거나 출결 상태를 수정하는 것들이 현재 라우터를 통해서 접근이 가능하다. HOC 방식으로 접근을 제어하고 있지만, 해당 페이지에서 `useState`로 `editMode`를 사용하는 것이 더 좋을듯.

### Todo
- [x] CoursePage에서 분리하기
- [x] AttendancePage에서 분리하기

**Comment by qqq1212341** [comment]
CoursePage는 좀 더 진행이 되면 하겠습니다~
