### ISSUE TITLE
Skeleton 효과 추가

### ISSUE THREAD

**Issue by qqq1212341** [kucc/KUCheckCheck#47]
# 설명
Data를 fetching하는 부분에서는 antd의 skeleton 효과를 추가하여 ux를 향상시킨다. Button, Avatar, Input 등 각 컴포넌트에 맞는 skeleton을 사용.
<hr/>

- [ ] 유저 페이지

- [ ] 출석 페이지

- [ ] 코스 상세 페이지

**Comment by Taewoong1378** [comment]
👍
